# Generated by Django 3.0.5 on 2020-08-03 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0018_auto_20200730_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='timedtask',
            name='cronId',
            field=models.TextField(null=True, verbose_name='计划名称'),
        ),
        migrations.AddField(
            model_name='timedtask',
            name='planId',
            field=models.TextField(null=True, verbose_name='计划名称'),
        ),
    ]
