# Generated by Django 3.0.5 on 2020-04-16 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(max_length=12, unique=True, verbose_name='手机号码'),
        ),
    ]
