# Generated by Django 3.0.5 on 2020-04-20 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_last_project',
            field=models.IntegerField(default=0, verbose_name='用户最后一次访问项目id'),
        ),
        migrations.AlterField(
            model_name='department',
            name='department_id',
            field=models.IntegerField(default=1, unique=True),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='user_group_id',
            field=models.CharField(choices=[(1, '查'), (2, '增查改'), (3, '增查改删')], default=1, max_length=2, unique=True),
        ),
    ]
