# Generated by Django 3.0.5 on 2020-04-16 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200416_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='name',
            field=models.CharField(default='研发部', max_length=10, verbose_name='部门'),
        ),
        migrations.AlterField(
            model_name='department',
            name='department_id',
            field=models.CharField(default=1, max_length=2, unique=True),
        ),
    ]
