# Generated by Django 3.0.5 on 2020-04-28 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterfaceFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filesName', models.CharField(max_length=255, verbose_name='接口文档名称')),
                ('post_attr', models.CharField(max_length=255, verbose_name='请求地址')),
                ('interface_detail', models.CharField(max_length=255, verbose_name='接口描述')),
                ('mock_attr', models.CharField(max_length=255, verbose_name='mock地址')),
                ('post_header', models.CharField(max_length=255, verbose_name='请求头')),
                ('post_data', models.CharField(max_length=255, verbose_name='请求数据')),
                ('res_header', models.CharField(max_length=255, verbose_name='返回头部')),
                ('res_data', models.CharField(max_length=255, verbose_name='返回数据')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'interface_files',
            },
        ),
        migrations.CreateModel(
            name='InterfaceFilesName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'interface_files_name',
            },
        ),
        migrations.CreateModel(
            name='PostMethods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='请求方法名称')),
            ],
            options={
                'db_table': 'post_methods',
            },
        ),
        migrations.CreateModel(
            name='PostType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='请求类型名称')),
            ],
            options={
                'db_table': 'post_type',
            },
        ),
        migrations.CreateModel(
            name='ProjectList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='项目名称')),
                ('dev_attr', models.CharField(max_length=100, verbose_name='开发地址')),
                ('test_attr', models.CharField(max_length=100, verbose_name='测试地址')),
                ('product_attr', models.CharField(max_length=100, verbose_name='生产地址')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'project_list',
            },
        ),
        migrations.CreateModel(
            name='ResType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='返回类型名称')),
            ],
            options={
                'db_table': 'res_type',
            },
        ),
    ]
