# Generated by Django 3.0.5 on 2020-04-20 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='项目名称')),
                ('dev_attr', models.CharField(max_length=100, verbose_name='开发地址')),
                ('test_attr', models.CharField(max_length=100, verbose_name='测试地址')),
                ('product_attr', models.CharField(max_length=100, verbose_name='生产地址')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(default='Null', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Project_list',
            },
        ),
    ]
